package com.inspinia.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.inspinia.entity.Member;

@Mapper
public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    Member  selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    List<Member> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    int updateByPrimaryKey(Member record);
}